# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  contentDir: content/en
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
  
  

# Uncomment the lines below to configure your website in a second language.
fr:
    contentDir: content/fr
    languageName: Français
    weight: 20
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
